spring.application.name=FilmdexBE
spring.datasource.url=jdbc:postgresql://localhost:8080/filmdex
spring.datasource.username=filmdex
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

// TODO: ADD FEATURES
