spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=filmdex
spring.datasource.password=filmdex

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

tmdb.api.token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0ZjcwNzE1MWMyNTI2N2RiYWRjNTYwODAxNjdhYjc1ZiIsIm5iZiI6MTc4MDI0NTY2OC42NzM5OTk4LCJzdWIiOiI2YTFjNjRhNDg3M2I0M2QxZGEwOGJmZTAiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.aeK2F7x77CTZLyh92iCrPUA5-0XO8TNJeVIIpBnVung