-- =======================================================
-- CREACIÓN DE USUARIO Y PERMISOS EN ORACLE
-- =======================================================
-- Nota: Si estás usando una base de datos Express (XE) o Multi-tenant (CDB/PDB)
-- ALTER SESSION SET "_ORACLE_SCRIPT"=true;        -- sólo en la creación

CREATE USER IF NOT EXISTS filmdex IDENTIFIED BY filmdex;
GRANT CONNECT, RESOURCE, CREATE VIEW TO filmdex;
ALTER USER filmdex QUOTA UNLIMITED ON USERS;

-- =======================================================
-- 1. TABLA: PERSONS (Directores y Actores)
-- =======================================================
CREATE TABLE persons (
                         id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR2(255) NOT NULL
);

-- =======================================================
-- 2. TABLA: MOVIES
-- =======================================================
CREATE TABLE movies (
                        id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR2(255) NOT NULL,
                        year NUMBER(10),
                        synopsis CLOB, -- TEXT cambia a CLOB en Oracle
                        director_id NUMBER(19),
                        CONSTRAINT fk_movie_director FOREIGN KEY (director_id) REFERENCES persons(id) ON DELETE SET NULL
);

-- =======================================================
-- 3. TABLA INTERMEDIA: MOVIE_CAST
-- =======================================================
CREATE TABLE movie_cast (
                            movie_id NUMBER(19) NOT NULL,
                            person_id NUMBER(19) NOT NULL,
                            PRIMARY KEY (movie_id, person_id),
                            CONSTRAINT fk_cast_movie FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE,
                            CONSTRAINT fk_cast_person FOREIGN KEY (person_id) REFERENCES persons(id) ON DELETE CASCADE
);

-- =======================================================
-- 4. TABLA: USERS
-- =======================================================
CREATE TABLE users (
                       id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR2(255),
                       username VARCHAR2(255) UNIQUE,
                       password VARCHAR2(255)
);

-- =======================================================
-- 5. TABLA: REVIEWS
-- =======================================================
CREATE TABLE reviews (
                         id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         user_id NUMBER(19) NOT NULL,
                         movie_id NUMBER(19) NOT NULL,
                         rating NUMBER(10) NOT NULL,
                         "comment" CLOB, -- ¡OJO! COMMENT es palabra reservada en Oracle, debe ir entre comillas dobles
                         CONSTRAINT uk_user_movie UNIQUE (user_id, movie_id),
                         CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                         CONSTRAINT fk_review_movie FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE
);

-- =======================================================
-- 6. TABLA DE COLECCIÓN: USER_WATCHED_MOVIES
-- =======================================================
CREATE TABLE user_watched_movies (
                                     user_id NUMBER(19) NOT NULL,
                                     movie_id NUMBER(19) NOT NULL,
                                     PRIMARY KEY (user_id, movie_id),
                                     CONSTRAINT fk_watched_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =======================================================
-- 7. TABLA DE COLECCIÓN: USER_FAVOURITE_MOVIES
-- =======================================================
CREATE TABLE user_favourite_movies (
                                       user_id NUMBER(19) NOT NULL,
                                       movie_id NUMBER(19) NOT NULL,
                                       PRIMARY KEY (user_id, movie_id),
                                       CONSTRAINT fk_favourite_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);